yarnPath: .yarn/releases/yarn-3.2.1.cjs

nodeLinker: node-modules

npmScopes:
  saas-ui:
    npmRegistryServer: 'https://npm.saas-ui.dev'
npmRegistries:
  //npm.saas-ui.dev:
    npmAuthIdent: '${SAAS_UI_TOKEN:-}'
    npmAlwaysAuth: true
